### ISSUE TITLE
Drop the use for django.utils.six

### ISSUE THREAD

**Issue by EricFelixLuther** [jazzband/django-dbtemplates#111]
Django 3.0 [dropped the support for the `six` library](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis). In order to keep up with evolving framework, this should be changed and fixed.

**Comment by ngkabra** [comment]
I ran into this issue and had to resolve it by installing `django-utils-six`. Until the dependency on `six` is removed, maybe `django-utils-six` should be added as a dependency for `django-dbtemplates`?

**Comment by ngkabra** [comment]
I ran into this issue and managed to fix it by installing `django-utils-six`. 

Until the use of `django.utils.six` is removed from `django-dbtemplates` maybe `django-utils-six` should be added as a dependency?

**Comment by emilkjer** [comment]
Duplicate https://github.com/jazzband/django-dbtemplates/pull/107

**Comment by hugovk** [comment]
`django.utils.six` was replaced by six in #107, and six and Python 2 dropped in https://github.com/jazzband/django-dbtemplates/pull/112.
