### ISSUE TITLE
Is this project deprecated?

### ISSUE THREAD

**Issue by whikloj** [jazzband/django-dbtemplates#121]
I'm new to Django and was pointed at this project as a suggestion. It fits my use case exactly (I think) but in trying to install it I am hitting a variety of errors. Most of these have been solved on the main branch or are sitting as PRs.

But as the most recent version of this package is 3 years old I am wondering if it has been deprecated/abandoned and if so, is there is a recommended replacement?

**Comment by jezdez** [comment]
I've just added @mpasternak to the project. The project is not deprecated per se, no.

**Comment by jezdez** [comment]
Oh before I forget, please make sure to read the docs about [releases](https://jazzband.co/about/releases), [guidelines](https://jazzband.co/about/guidelines), [security](https://jazzband.co/about/security) and [FAQ](https://jazzband.co/about/faq). And a gentle reminder that you agree to follow the Jazzband [Code of Conduct](https://jazzband.co/about/conduct).

**Comment by mpasternak** [comment]
Thank you. I will.
