### ISSUE TITLE
New release on PyPi, maybe?

### ISSUE THREAD

**Issue by mpasternak** [jazzband/django-dbtemplates#124]
Hello, 

last release 3.0 on PyPi is from Jan 2019. 

How about releasing a new one... ?

**Comment by mpasternak** [comment]
@jezdez bump.

**Comment by VedranID** [comment]
Hi!

Any news on the new PyPi release? I see the support for Django 3.2 has been merged into master and I would appreciate being able to pull it from PyPi.

Thank you!

**Comment by hugovk** [comment]
Unfortunately @jezdez is the [only roadie](https://jazzband.co/roadies) and only roadies can give those permissions.

See also https://github.com/jazzband/help/issues/196.

**Comment by mpasternak** [comment]
I created a separate issue on jazzband, https://github.com/jazzband/help/issues/309

**Comment by mpasternak** [comment]
4.0 released, thanks for everyone involved
