### ISSUE TITLE
Disable cacheing (Fixed in new version?)

### ISSUE THREAD

**Issue by bbirand** [jazzband/django-dbtemplates#77]
Hi,

Thanks for dbtemplates, I'm looking forward to trying it. I'm running Django==1.9.7, and having trouble setting up this module. When I try to set it up, I get the error:

```
ImportError: cannot import name 'get_cache'
```

I think this is fixed in the new version, but not on the one in PyPI (version 1.3). Can you push the latest version to PyPI.

Also, is there any way to cancel cacheing altogether?

Thanks

**Comment by jezdez** [comment]
Yeah, will be fixed in #81
