### ISSUE TITLE
Project Lead.

### ISSUE THREAD

**Issue by wsantos** [jazzband/django-dbtemplates#93]
I've been using this module on my recent projects and I'd like to help it.

**Comment by wsantos** [comment]
@jezdez Do I need to do anything extra here?

**Comment by jezdez** [comment]
@wsantos Please let me know if you're still interested.

**Comment by jezdez** [comment]
Update: I've re-enabled the release system so any tag pushed to the repo will result in an email to the project lead (myself right now) to confirm the release.

**Comment by wsantos** [comment]
@jezdez I can't take the lead now, but I will definitely be helping whenever I can. Thanks for fixing the release.

**Comment by jezdez** [comment]
Understood. Closing..
